name: Update graphql introspection

on:
  repository_dispatch:
    types: [ schema ]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout server repo
        uses: actions/checkout@v3
        with:
          repository: santa-close/santa-closer-server
          path: server
          
      - name: Setup node.js
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          
      - name: Generate introspection
        working-directory: ./server
        run: |
          yarn
          yarn generate
          cp ./introspection.json ../main/
        
      - name: Echo 
        working-directory: ./main
        run: cat introspeciton.json
