name: Update graphql introspection

on:
  repository_dispatch:
    types: [ schema ]
  pull_request:
    branches:
      - main

jobs:
  schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout server repo
        uses: actions/checkout@v3
        with:
          repository: santa-close/santa-close-server
          ref: main
          
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install
        
      - run: cat package.json
          
      - name: Generate introspection
        run: yarn run generate

      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          path: main-repo
          ref: main
          
      - name: Commit introspection.json
        working-directory: ./main-repo
        run: |
          cp ../introspection.json .
          git add introspection.json
          git commit -m "update introspection"
          git push
          
