name: Update graphql introspection

on:
  repository_dispatch:
    types: [ schema ]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout server repo
        uses: actions/checkout@v3
        with:
          repository: santa-close/santa-close-server
          ref: main
          
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          
      - name: Generate introspection
        run: |
          yarn
          yarn generate

      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          path: main-repo
          ref: main
          
      - name: Commit introspection.json
        working-directory: ./main-repo
        run: |
          cp ../introspection.json .
          git add introspection.json
          git commit -m "update introspection"
          git push
          
